### ISSUE TITLE
Possible chosen plaintext attack

### ISSUE THREAD

**Issue by dushankw** [PurritoBin/PurritoBin#2]
```
# POSIX shell client to upload standard message
purr() {
	curl --silent --data-binary "@${1:-/dev/stdin}" bsd.ac:42069;
}
# POSIX shell client to upload encrypted message
meow() {
	key="$(openssl rand -hex 32)"
	url="$(openssl enc -aes-256-cbc -K ${key} -iv 00000000000000000000000000000000 -e -base64 -A < ${1:-/dev/stdin} | purr)"
	echo "${url%\/*}/paste.html#${url##*\/}_${key}"
}
```

Hi,

In this code snippet (https://github.com/PurritoBin/PurritoBin/blob/master/README.md) you are using an all-zero IV, when using AES in CBC mode this often creates the possibility for a chosen plain-text attack.

In your case, a new key is being used every time, but there is still the potential for issues https://crypto.stackexchange.com/questions/58060/is-zero-iv-with-aes-cbc-safe-if-cpa-is-not-possible-and-indistinguishability-is

More generally, all-zero IVs is an anti-pattern that should not be advocated, particularly as someone may come across this code and copy it into something else without realising the implications (especially if they end up re-using a key).

Just making the observation, perhaps there is some design consideration here I am overlooking, however allowing `openssl` to generate a random IV seems like a better thing to do, if you're base64 encoding the whole thing anyhow there is no overhead with transmitting it.

Finally, your command may default to using a weak KDF (modern openssl versions will warn about this), it would be better to explicitly specify, something like `-pbkdf2` should be broadly compatible between openssl versions and still adequately secure.

Best,
Dushan

**Comment by epsilon-0** [comment]
> Hi,
> 

Thanks so much for your interest!!

> In this code snippet (https://github.com/PurritoBin/PurritoBin/blob/master/README.md) you are using an all-zero IV, when using AES in CBC mode this often creates the possibility for a chosen plain-text attack.
> 
> In your case, a new key is being used every time, but there is still the potential for issues https://crypto.stackexchange.com/questions/58060/is-zero-iv-with-aes-cbc-safe-if-cpa-is-not-possible-and-indistinguishability-is
> 
> More generally, all-zero IVs is an anti-pattern that should not be advocated, particularly as someone may come across this code and copy it into something else without realising the implications (especially if they end up re-using a key).
> 

This is a very valid point, copy pasting things is a problem, when people do it without trying to understand the security.

> Just making the observation, perhaps there is some design consideration here I am overlooking, however allowing `openssl` to generate a random IV seems like a better thing to do, if you're base64 encoding the whole thing anyhow there is no overhead with transmitting it.
> 
> Finally, your command may default to using a weak KDF (modern openssl versions will warn about this), it would be better to explicitly specify, something like `-pbkdf2` should be broadly compatible between openssl versions and still adequately secure.
> 

**KDF** = key derivation function, needed to generate encryption key from a supplied key. Here we are directly supplying the encryption key, so `kdf` does not come into play.

`-pbkdf2` is needed when supplying a key (usually human memorable), using `-k`, note the **smaller case**, which is used to generate the `key` and `IV` and then encrypting it.

You can see this, as adding `-pbkdf2` option does not change the output, e.g.
```
$ key="$(openssl rand -hex 32)"  # say, 9a0110baea8d14a37f9f16549ed1f1f88ac397d481d1fedf03d8d19550814a2d 
$ cipher="ThisIsACipher"
$ printf "%s" $cipher | openssl enc -aes-256-cbc -K ${key} -iv 00000000000000000000000000000000 -e -base64 -A
HOzrK9JWxxEAr9dDRgRt9g==
$ printf "%s" $cipher | openssl enc -aes-256-cbc -pbkdf2 -K ${key} -iv 00000000000000000000000000000000 -e -base64 -A
HOzrK9JWxxEAr9dDRgRt9g==
```

Would love to know if there is a different method to do this.

> Best,
> Dushan

Thanks,
Aisha

**Comment by dushankw** [comment]
Regarding the KDF, you are correct. 

I believed the `-K` option was to supply a password non-interactively that would be passed into the KDF to derive the final encryption key, a re-consultation of the man page proves me incorrect (as you say, this option is the lower case `-k`) so please disregard this point.

In terms of the IV though, I believe that my points stand, both in terms of advocating a generally unsafe pattern and the specific issues that could apply in your implementation.

Here is how I believe it could be solved:

### Generate your key and iv, encrypt the data

```
$ key="$(openssl rand -hex 32)"
$ echo $key
1b869c06b7fb34bd025ec0a2c5d1c0362d277dd6d2afdf734b36bac6433aaed4

$ iv="$(openssl rand -hex 16)"
$ echo $iv
2783fc7200207d5f6b958208940322c1

$ encrypted="$(echo 'super secret stuff' | openssl enc -aes-256-cbc -K ${key} -iv ${iv} -e -base64 -A)"
$ echo $encrypted
BYs9QcNxAmcTMVFjaRv6S0dNImjfvLDrLPDif7NuE1g=
```

### Store the resulting base64 encoded ciphertext and iv

```
$ result="${encrypted}:${iv}"
$ echo $result
BYs9QcNxAmcTMVFjaRv6S0dNImjfvLDrLPDif7NuE1g=:2783fc7200207d5f6b958208940322c1
```

NOTE `:` is not part of the base64 charset so is a safe delimiter and the iv does not need to be a secret (https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Initialization_vector_.28IV.29)

You may now forward your `$result` wherever you like.

### To decrypt we split our `$result` on the `:` and use it along with the key to decrypt

```
$ result='BYs9QcNxAmcTMVFjaRv6S0dNImjfvLDrLPDif7NuE1g=:2783fc7200207d5f6b958208940322c1'
$ decryption_input=(${result//:/ })

$ echo ${decryption_input[0]}
BYs9QcNxAmcTMVFjaRv6S0dNImjfvLDrLPDif7NuE1g=

$ echo ${decryption_input[1]}
2783fc7200207d5f6b958208940322c1

$ echo ${decryption_input[0]} | openssl enc -aes-256-cbc -base64 -d -K ${key} -iv ${decryption_input[1]}
super secret stuff
```

Some of the echo statements can clearly be omitted, they are just for illustration purposes.

Commands tested in GNU bash, version 5.0.17(1)-release

Best,
Dushan

**Comment by dushankw** [comment]
You may also prefer to use `printf` or `echo -n` if trailing newlines are an issue.

**Comment by epsilon-0** [comment]
OK, I will add the part for using a generated IV, but note that this does not add any security benefit whatsoever.
The current config does not have any issues with chosen plaintext attacks.

The only reason to add this would be to make it so that people who copy paste will not be adversely affected.

**Comment by dushankw** [comment]
So long as a unique key is definitely always used then yes, re-considering the situation, everything should be mitigated.

It is your decision, however, I still do feel there is the potential for such a command to be used unsafely. In any case, thanks for your consideration of the issue.

Best,
Dushan
