### ISSUE TITLE
Server is returning empty replies

### ISSUE THREAD

**Issue by ericonr** [PurritoBin/PurritoBin#6]
Hi! Long time no see :)

I noticed some issues with my client, but figured there had been some server side change I needed to adapt to, so I didn't pursue it. I went to look now into what had changed, but it seems even the suggested client with curl is failing... After removing `--quiet` from it:

```
/tmp 🐍 ➜ ./purr cleanlog
curl: (52) Empty reply from server
```

Pasting via web interface directly in <bsd.ac> appears to be working ok.

**Comment by epsilon-0** [comment]
The server got updated to use TLS. So the default client is now 
```
: ${P_SERVER="https://bsd.ac"}
: ${P_PORT=42069}
: ${P_MAXTIME=30}
: ${_PL=week} # can be set to day/week/month/<lifetime-in-minutes>
purr() {
	curl --silent --max-time "${P_MAXTIME}" --data-binary "@${1:-/dev/stdin}" "${P_SERVER}:${P_PORT}/${_PL}"
}
```

**Comment by ericonr** [comment]
Indeed, it's working! Thanks
